import sys
import os
# Add parent directory (lib/) to Python's search path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from cash_register import CashRegister

print("=" * 60)
print("TEST 1: Adding items")
print("=" * 60)
register = CashRegister()
print(f"Initial total: ${register.total}")

register.add_item("apple", 1.50, 3)
print(f"After adding 3 apples at $1.50 each:")
print(f"  Total: ${register.total}")
print(f"  Items: {register.items}")
print(f"  Previous transactions: {register.previous_transactions}")

register.add_item("bread", 2.50, 1)
print(f"After adding 1 bread at $2.50:")
print(f"  Total: ${register.total}")
print(f"  Items: {register.items}")
print(f"  Previous transactions: {register.previous_transactions}")
print()

print("=" * 60)
print("TEST 2: Apply discount - with 20% discount")
print("=" * 60)
register2 = CashRegister(20)
register2.add_item("shirt", 25.00, 2)
print(f"Total before discount: ${register2.total}")
register2.apply_discount()
print(f"Total after discount: ${register2.total}")
print()

print("=" * 60)
print("TEST 3: Apply discount - with no discount")
print("=" * 60)
register3 = CashRegister()
register3.add_item("book", 15.00, 1)
print(f"Total: ${register3.total}")
register3.apply_discount()
print()

print("=" * 60)
print("TEST 4: Void last transaction")
print("=" * 60)
register4 = CashRegister()
register4.add_item("coffee", 4.50, 2)
register4.add_item("muffin", 3.00, 1)
print(f"Total before void: ${register4.total}")
print(f"Items before void: {register4.items}")
print(f"Transactions before void: {register4.previous_transactions}")

register4.void_last_transaction()
print(f"Total after void: ${register4.total}")
print(f"Items after void: {register4.items}")
print(f"Transactions after void: {register4.previous_transactions}")
print()

print("=" * 60)
print("TEST 5: Void with no transactions")
print("=" * 60)
register5 = CashRegister()
register5.void_last_transaction()
print()

print("=" * 60)
print("TEST 6: Complete workflow")
print("=" * 60)
register6 = CashRegister(15)
print("Starting a new transaction with 15% discount...")
register6.add_item("laptop", 1000.00, 1)
register6.add_item("mouse", 25.00, 2)
print(f"Total before discount: ${register6.total}")
print(f"Items: {register6.items}")

register6.apply_discount()
print(f"Final total: ${register6.total}")